spring.application.name=parkease

server.port=9292

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/parkease
spring.datasource.username=root
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key=rzp_test_SauO5cr62cK57R
razorpay.secret=TsvO58kDejP7ewQbAqaA1p2q
